### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Rezie1234** [qbcore-framework/qb-scrapyard#24]
**Describe the bug**
Hello, I'm using QB-targeting and have created a ped so that I can have him distribute the scraplist so like a chopshop, I'm really struggling. I can third eye him and it's giving me the prompt to ask for the list but when I then click I get nothing. I have created the new event in the scrap files, and also posted the script in the Qb targeting files. 

![image](https://user-images.githubusercontent.com/112276242/187044430-bc962952-1e4e-4821-8a68-278eeaddb330.png)
![image](https://user-images.githubusercontent.com/112276242/187044454-4f690c86-78a9-41da-ac93-2bdf98a3cf92.png)
![image](https://user-images.githubusercontent.com/112276242/187044488-f02ac090-2356-4bf7-9cbc-fb528ffbb671.png)
![image](https://user-images.githubusercontent.com/112276242/187044498-d80d04a2-551f-421d-8c7b-ab319d1e6444.png)

**Expected behavior**
Talk to NPC, get the scrap list.

**Comment by singh-manavv** [comment]
Where are you triggering the setNewVehicles event ?

**Comment by Rezie1234** [comment]
In the Init.lua as there was no config on that file.

**Comment by singh-manavv** [comment]
> In the Init.lua as there was no config on that file.

It seems you're triggering the getVehicles event in init.lua , not setNewVehicles ,

**Comment by singh-manavv** [comment]
So according to the code i see you attached here , it seems you're triggering the getVehicles event from init and that event triggers the CreateListEmail function , and there's no preview of that code

**Comment by Rezie1234** [comment]
Perfect mate thanks. I've got the first part working now, appreciate it.

**Comment by singh-manavv** [comment]
okay perfect!

**Comment by Rezie1234** [comment]
I've ffixed all this now manav. Just trying to fix the random blips
