### ISSUE TITLE
[BUG] QB-SCRAPYARD

### ISSUE THREAD

**Issue by Knuffelpanda** [qbcore-framework/qb-scrapyard#30]
I'm you use the qb-scrapyard. But i have use it like drawtext not target use. Now you have two place in this scrapyard one for a disassemble vehicle and one to get the list. I am using dutch translation. 

**Screenshots**
List location:
https://i.imgur.com/IUshlsX.png

Disassemble location:
https://i.imgur.com/m0FuynY.png

 - When you last updated: last week
 - Are you using custom resource? which ones? none clean install

**Comment by Killerhunter100** [comment]
could you please explain what is the issue

**Comment by ImBeefy** [comment]
I have the same issue, any fix to this?

It either shows "Email Vehicle List" or "Dissemble Vehicle" in both Vector3 places.

**Comment by AnishBplayz** [comment]
I tried reproducing the issue, doesn't seem a bug to me
